#!/bin/sh
LUA="lua"
CC="gcc"

while [ $# -gt 0 ]
do
    case "$1" in
        (*=*) eval $1;;
        -h|--help)  echo "optionally LUA=lua,  PLAT=plat, CC=cc, LUA53=1"; exit;;
    esac
    shift
done

if [ -z LUA53 ]
then
   SOURCE='lua-5.2.2'
   LUAVS=''
else
   SOURCE='lua-5.3.0/src'
   LUAVS='LUA53=1'
fi

quiet () {
    cmd=$1
    shift
    env $cmd $* 2>&1  > /dev/null
}

if ! quiet which $CC
then
    echo "compiler $CC cannot be found"
    exit
else
    if [ "$CC" != "gcc" ]
    then
        CC="CC=$CC"
    else
        CC=''
    fi
fi

if quiet which $LUA
then
    if ! quiet $LUA -llfs -e "print(1)"
    then
        echo "Please install LuaFileSystem"
        exit
    fi
else # have to bootstrap!
    echo "$LUA not found, bootstrapping"
    if [ -z "$PLAT" ]
    then
        case "$(uname)" in
             "Linux" ) PLAT=linux;;
             "Darwin" ) PLAT=macosx;;
             *            ) PLAT=posix;;
        esac
        pushd $SOURCE
        if ! make $PLAT
        then
            echo "bootstrap build borked"
            exit
        fi
        rm lua.o loadlib.o
        popd
        . setpath
        LUA=luaboot
    fi
fi

# now let Lake do the hard part ...
CMD="env $LUA lake $CC $LUAVS"
echo $CMD
if $CMD
then
    env $LUA lake install.lua $LUA53
fi

 


