#!/bin/bash

. setpath

while [ $# -gt 0 ]
do
    case "$1" in
        (*=*) eval $1;;
        -h|--help)  echo "optionally LUA53=1, STATIC=1"; exit;;
    esac
    shift
done

if [ -z LUA53 ]
then
    L53=''
    L='lua52'
else
    L53='L53=1'
    L='lua53'
fi

# see if we can build luaish properly!
pushd luaish
soar -o luaish lua.lua -lconfig -lluaish.lua < t.lua
srlua -o ../bin/luaish -l $L luaish
popd
if ! luaish < luaish/t.lua
then
    echo "luaish test borked"
    exit
fi

lake -f test.lake $L53
